### ISSUE TITLE
cryptdb add a static library

### ISSUE THREAD

**Issue by Rafoula** [agribu/cdb-wiki#1]
Hello,
I am studying on the Cryptdb and I want to add the static library .a (the static library is a second project which I want to call it for functions) in the Cryptdb and after I want to call some functions from static library .a .
Could you help me please how to add the static library?

Thanks!

**Comment by agribu** [comment]
Unfortunately I don't know how to help you with this. However, please let me know if you find a solution as it would also be of my interest.

**Comment by Rafoula** [comment]
create your second project as a static library (.a) and move the static library,headers files in local folder
